### ISSUE TITLE
YAML output not compliant with standard

### ISSUE THREAD

**Issue by omaralvarez** [exmatex/CoMD#5]
After several hours trying to debug an issue while plotting performance results, thinking there was an issue with my R script, I have realised that the YAML output is not compliant with standard version 1.2. As is, when using a YAML parser there is a `Scanner error: mapping values are not allowed in this context`.

The problematic chunk of the output is for example:

```yaml
Performance Results For Rank 0:
  Timer: total
    CallCount:  1
    AvgPerCall:   6.0009
    Total:        6.0009
    PercentLoop:   101.79
  Timer: loop
    CallCount:  1
    AvgPerCall:   6.0009
    Total:        6.0009
    PercentLoop:   101.79
```

It should instead output:

```yaml
Performance Results For Rank 0:
  - Timer: total
    CallCount:  1
    AvgPerCall:   6.0009
    Total:        6.0009
    PercentLoop:   101.79
  - Timer: loop
    CallCount:  1
    AvgPerCall:   6.0009
    Total:        6.0009
    PercentLoop:   101.79
```
